### ISSUE TITLE
Ultrawide locked to 16:9

### ISSUE THREAD

**Issue by ActualMandM** [korenkonder/DivaGL#1]
Using an Ultrawide resolution (1720x720 in this case) with DivaGL will make the game render at 16:9 with the 3D squished to the viewport.

Without DivaGL:
![2023-12-28_16-42-15_diva](https://github.com/korenkonder/DivaGL/assets/15317421/b0892da0-a04d-408f-8133-fb4bea442db7)

With DivaGL:
![2023-12-28_16-43-04_diva](https://github.com/korenkonder/DivaGL/assets/15317421/042ccbd7-0d50-40e4-8e38-c39ad15f58a1)

**Comment by korenkonder** [comment]
Fixed that.

**Comment by korenkonder** [comment]
Fixed that.
