### ISSUE TITLE
Invisible Pause Menu

### ISSUE THREAD

**Issue by xjunko** [korenkonder/DivaGL#2]
## Details
GPU: GTX 1050TI
and for PDAFT afaict everything (the plugins) are all on the latest version.

## Image(s)
![image](https://github.com/korenkonder/DivaGL/assets/44401509/594e5dff-6a05-4804-af23-92a27a5709cb)
(Doesn't help out much but this is paused ingame, and the menu is not there.)

**Comment by Johnsen290** [comment]
Use the unstable newest, worked for me on Intel HD 4400.

**Comment by rexbuba** [comment]
I can confirm that the lastest test build correct this issue.

**Comment by korenkonder** [comment]
Try using this:
https://github.com/PDModdingCommunity/PD-Loader/wiki/Latest-test-build
