### ISSUE TITLE
all character are black eyes

### ISSUE THREAD

**Issue by HatsuneMikuMirai** [korenkonder/DivaGL#3]
the problem is some in linux(wine) 

![Captura de tela de 2024-03-15 16-22-42](https://github.com/korenkonder/DivaGL/assets/162862780/ad5bb371-b25f-4e06-aed7-13dd4d41979b)

### My Hardware ###
GPU: Rx 7600
CPU: Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz
MOTHERBOARD: ASUSTeK COMPUTER INC. PRIME H310M-E R2.0/BR
RAM: 8GB

### LOG ### 

0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
0098:fixme:wineusb:query_id Unhandled ID query type 0x5.
[DivaGL] Current version - v0.4.4.0
[DivaGL] Attach
[DivaGL] Patching memory
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0120:fixme:ntdll:NtQuerySystemInformation (0x00000007,0x6c8718,0x00000018,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x00000050,0x6c8718,0x000000a8,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
0120:fixme:ntdll:NtQuerySystemInformation (0x00000021,0x6c88a0,0x00000010,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000002d,0x6c88a0,0x00000020,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000003d,0x6c88b8,0x00000a58,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x00000012,0x6c88b8,0x00000a58,0x11d390) stub
0120:fixme:ntdll:NtQuerySystemInformation (0x0000002a,0x6c88d0,0x00000a40,0x11d390) stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF7CF25B7, 28) stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF799CDE4, 28) stub
0120:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000011D818
0120:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscordacwks.dll", 00006FFFF71A0000) stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF702AEF1, 28) stub
[GPUModel] Checking GPU model
[Novidia] Hooking glutSetCursor
[Novidia] Hooking wglGetProcAddress
[Novidia] Hooking uploadModelTransformBuf
[Novidia] Hooking divaGetFileSize
[Novidia] Hooking divaFsopen
[Novidia] Hooking divaFread
[Patches] Game version 7.10
[Patches] Stereo patch enabled
[Patches] Show FREE PLAY instead of CREDIT(S)
[Patches] Show PD Loader text
[Patches] Cursor enabled
[Patches] Movies disabled
[Patches] Errors Banner disabled
[Patches] Patches applied
[Patches] Reading custom patches...
[Patches] Skipping disabled patch file: custom_freeplay_text_example.p
[Patches] All custom patches applied
[Render] Custom internal resolution enabled
[Render] X: 1920 Y: 1080
[GPUModel] Checking GPU model
[ShaderPatch] Detected GPU: AMD
[TLAC] DllMain(): Installing hooks...
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
0120:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
0120:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000011FB44
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 0x416 000000000011D124 0000000000000000 000000000011D120) returning a dummy value (current locale)
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 0x416 000000000011D124 0000000019CEDA50 000000000011D120) returning a dummy value (current locale)
0120:fixme:ntdll:NtQuerySystemInformation (0x000000ce,0x11e1e0,0x00000008,(nil)) stub
0120:fixme:bcrypt:BCryptGetFipsAlgorithmMode 000000000011DF80 - semi-stub
0120:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 000000000160DEA0, 51) stub
0120:fixme:font:find_matching_face Untranslated charset 255
0120:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\TTF\\odokai-ExtB.ttf"
0120:fixme:gdiplus:GdipGetFamilyName No support for handling of multiple languages!
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {c3fcc19e-a970-11d2-8b5a-00a0c9b7c9c4}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {b196b283-bab4-101a-b69c-00aa00341d07}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {af86e2e0-b12d-4c6a-9c5a-d7aa65101e90}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {ecc8691b-c1db-4dc0-855e-65f6c551af49}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {94ea2b94-e9cc-49e0-c0ff-ee64ca8f5b90}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {00000003-0000-0000-c000-000000000046}
0120:fixme:olepicture:OLEPictureImpl_QueryInterface () : asking for unsupported interface {00000144-0000-0000-c000-000000000046}
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
0120:fixme:gdiplus:GdipGetLineSpacing ignoring style
[DivaWig] Hooking functions...
[DivaWig] Functions hooked.
[DSCRemote] Hooking functions...
[DSCRemote] Functions hooked.
013c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 000000001BD0FF50
[DSCRemote] Staring server...
[DSCRemote] Waiting for client...
0120:fixme:virtual:NtFlushProcessWriteBuffers stub
0120:fixme:dwmapi:DwmSetWindowAttribute (0000000000010072, 14, 000000000011F880, 4) stub
[GPUModel] Checking GPU model
0120:fixme:gdiplus:GdipCreateHalftonePalette stub
0144:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0144:fixme:seh:WerSetFlags (2) stub
0144:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
0144:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0154:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
0154:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 780E3241, 28) stub
0160:fixme:seh:WerSetFlags (2) stub
0160:fixme:heap:RtlSetHeapInformation HEAP_INFORMATION_CLASS 1 not implemented!
016c:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
016c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF7CF25B7, 28) stub
0154:fixme:service:QueryServiceConfig2W Level 6 not implemented
0154:fixme:service:QueryServiceConfig2W Level 6 not implemented
0154:fixme:service:QueryServiceConfig2W Level 6 not implemented
0154:fixme:service:QueryServiceConfig2W Level 6 not implemented
016c:fixme:service:QueryServiceConfig2W Level 6 not implemented
016c:fixme:service:QueryServiceConfig2W Level 6 not implemented
016c:fixme:service:QueryServiceConfig2W Level 6 not implemented
016c:fixme:service:QueryServiceConfig2W Level 6 not implemented
0154:fixme:service:QueryServiceConfig2W Level 6 not implemented
016c:fixme:service:QueryServiceConfig2W Level 6 not implemented
[wagner@archlinux PDAFT]$ 0184:fixme:font:get_gasp_flags Unsupported gasp table: ver 65535 size 8 recs 1
0184:fixme:font:get_gasp_flags Unsupported gasp table: ver 65535 size 8 recs 1
017c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
017c:fixme:ntdll:NtQuerySystemInformation (0x00000007,0x6c87c8,0x00000018,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation (0x00000050,0x6c87c8,0x000000a8,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_CACHE_INFORMATION
017c:fixme:ntdll:NtQuerySystemInformation (0x00000021,0x6c8950,0x00000010,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation (0x0000002d,0x6c8950,0x00000020,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation (0x0000003d,0x6c8968,0x00000a58,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation (0x00000012,0x6c8968,0x00000a58,0x11d390) stub
017c:fixme:ntdll:NtQuerySystemInformation (0x0000002a,0x6c8980,0x00000a40,0x11d390) stub
017c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF7CF25B7, 28) stub
0184:fixme:font:get_gasp_flags Unsupported gasp table: ver 65535 size 8 recs 1
017c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF6DBCDE4, 28) stub
017c:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000011D818
017c:fixme:seh:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\mscordacwks.dll", 00006FFFF65C0000) stub
017c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00006FFFF7BFAEF1, 28) stub
0184:fixme:font:get_gasp_flags Unsupported gasp table: ver 65535 size 8 recs 1
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {72b14a7d-704c-423e-92f8-7e6d64bcb92a}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2091f8a-1e0a-4731-84a2-0dd57c8a5261}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e8a3bf1f-a86b-4390-9c60-5390b969d22c}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {5727a00f-50be-4519-8256-f7699871fecb}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {7e854ec7-cdc4-405a-b5b2-aaf7c9e7d40c}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {79a60dc6-5fc8-4952-a41c-1163aeec5eb8}
017c:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {2718d25b-5bf5-4479-8e88-babc64bdbfca}
017c:fixme:heap:GetNumaHighestNodeNumber semi-stub: 000000000011FB44
019c:fixme:ver:GetCurrentPackageId (000000001AF3FF50 0000000000000000): stub
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:MMDevice_Activate IID_IDeviceTopology unsupported
017c:fixme:mmdevapi:client_GetSharedModeEnginePeriod (000000000080AEC0)->(000000000011F490, 000000000011F4C0, 000000000011F488, 000000000011F4BC, 000000000011F4B8) - stub
017c:fixme:nls:get_dummy_preferred_ui_language (0x8 0x416 000000000011C8D4 0000000000000000 000000000011C8D0) returning a dummy value (current locale)
017c:fixme:nls:get_dummy_preferred_ui_language (0x8 0x416 000000000011C8D4 000000002A17D830 000000000011C8D0) returning a dummy value (current locale)
017c:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 00000000015A93C0, 51) stub
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
^C
[wagner@archlinux PDAFT]$ 017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:elf_search_auxv can't find symbol in module
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!
017c:fixme:dbghelp:x86_64_fetch_minidump_module RunTime_Function outside IMAGE_DIRECTORY_ENTRY_EXCEPTION unimplemented yet!

**Comment by korenkonder** [comment]
Sadly I don't have access to any machine with Linux installed. Though I have AMD CPU with Radeon Vega 8 Graphics I couldn't reproduce the issue.

**Comment by HatsuneMikuMirai** [comment]
Ok, I hope I've helped.

**Comment by HatsuneMikuMirai** [comment]
you can test this in WSL? on windows 11 probably you can reproduce

**Comment by Ramen2X** [comment]
I know Linux issues may not be in the scope of this project, but I managed to narrow this issue down further, so I thought I'd share anyways in case it's helpful. 

This is a problem with the OpenGL implementation in AMD's open source Linux drivers; the ones that 99.9% of people will be using. However, the OpenGL implementation in the proprietary, closed source [AMDGPU PRO drivers](https://wiki.archlinux.org/title/AMDGPU_PRO) on Linux do not cause this problem. Fortunately, AMD's closed source OpenGL implementation runs in user space on top of the open source drivers, so it's quite easy to apply these specifically for AFT and not system-wide.

Using the proprietary drivers for AFT gets everything looking great on my Linux machine, although I understand this might not be an ideal solution.

![image](https://github.com/korenkonder/DivaGL/assets/64166386/0394dc19-3e6c-4e4d-8d74-a2681da40e36)

**Comment by HatsuneMikuMirai** [comment]
> I know Linux issues may not be in the scope of this project, but I managed to narrow this issue down further, so I thought I'd share anyways in case it's helpful.
> 
> This is a problem with the OpenGL implementation in AMD's open source Linux drivers; the ones that 99.9% of people will be using. However, the OpenGL implementation in the proprietary, closed source [AMDGPU PRO drivers](https://wiki.archlinux.org/title/AMDGPU_PRO) on Linux do not cause this problem. Fortunately, AMD's closed source OpenGL implementation runs in user space on top of the open source drivers, so it's quite easy to apply these specifically for AFT and not system-wide.
> 
> Using the proprietary drivers for AFT gets everything looking great on my Linux machine, although I understand this might not be an ideal solution.
> 
> ![image](https://private-user-images.githubusercontent.com/64166386/327968926-0394dc19-3e6c-4e4d-8d74-a2681da40e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTYzMTgsIm5iZiI6MTcxNTA1NjAxOCwicGF0aCI6Ii82NDE2NjM4Ni8zMjc5Njg5MjYtMDM5NGRjMTktM2U2Yy00ZTRkLThkNzQtYTI2ODFkYTQwZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA0MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiY2FiOWNlNmQ1OTY3ZTMxNGUwODBkMTBkMzRmOWIwNmE0NzMwM2FiM2YyMzA3NDM4ZmQwZTA4OWRmMDE4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xS2sL-iFdr2tujHOmOBwcqPBO8Mavz9b6Dv7X2RtXe0)

Well the problem is resolve thanks, this issue shoube be closed as resolve

**Comment by Ramen2X** [comment]
I've just tested this again today with the latest DivaGL. As of this comment's writing, this issue is fully resolved. The game now renders properly with the open source AMD drivers on Linux.
