### ISSUE TITLE
Found invisible grass on Ievan Polka PV, and invisible stairs/sky/purple gradient in Rolling Girl PV, using Intel HD 4400, most are fine.

### ISSUE THREAD

**Issue by Johnsen290** [korenkonder/DivaGL#4]
title

**Comment by korenkonder** [comment]
Can you please provide screenshot of this happening?

**Comment by Johnsen290** [comment]
Ievan Polka:
![diva 2024-03-19 00-20-25-991](https://github.com/korenkonder/DivaGL/assets/79827112/a245c934-6794-401a-a4e4-2a502c1ed139)
![diva 2024-03-19 00-20-57-551](https://github.com/korenkonder/DivaGL/assets/79827112/1f310cbf-fa49-415d-b575-23110c7a5b85)
Rolling Girl:
![diva 2024-03-19 00-30-29-215](https://github.com/korenkonder/DivaGL/assets/79827112/50a0e089-b027-4755-b888-b9255abd195b)
![diva 2024-03-19 00-30-46-226](https://github.com/korenkonder/DivaGL/assets/79827112/464494e4-c88c-424f-8cd9-c4725f2470eb)
Rolling Girl (F2nd Edition):
![diva 2024-03-19 00-34-40-765](https://github.com/korenkonder/DivaGL/assets/79827112/f8faadfe-f23e-4a43-b682-a673c0345f14)
![diva 2024-03-19 00-35-01-282](https://github.com/korenkonder/DivaGL/assets/79827112/0cd7437f-753b-418c-a834-880b7b414c72)

Tried lots of things to work around this, Novidia, ShaderPatch, combinations of settings but to no avail, seems to be fine for most stages.

**Comment by korenkonder** [comment]
Please check the base game files.
Game looks right on my side (schreenshot 1) until I remove Auth3D stuff (schreenshot 2). That's not a DivaGL issue.
![image](https://github.com/korenkonder/DivaGL/assets/16868747/db16fd53-5c9a-43b3-a6c0-626b78ec61d6)
![image](https://github.com/korenkonder/DivaGL/assets/16868747/4bd0517b-722b-4c0a-9ca3-c9e64f18caae)

**Comment by Johnsen290** [comment]
Ah, sure, will reinstall them
