### ISSUE TITLE
Crash when Frame rate manager is active

### ISSUE THREAD

**Issue by rexbuba** [korenkonder/DivaGL#6]
CPU: AMD 3600X
GPU: AMD RX 6700XT
RAM: 16 GB 3200Mhz

The game crash in the select song menu after a few seconds when the Frame rate manager is active, disable Frame rate manager correct this behavior. I don´t known if the issue is relate to divagl but before i have in the same computer a gtx 1650 super and this not happen. Please forgive the bad grammar english is not my native language.

**Comment by korenkonder** [comment]
Try using this:
https://github.com/PDModdingCommunity/PD-Loader/wiki/Latest-test-build

**Comment by rexbuba** [comment]
Thank you so much for reply. This is maybe is too late, but first of all thank you for this amazing job. The test bulid that you provided  i can confirm that solve the issue including the other issue that i also experiment: the issues was invisible menu during songs. Thanks for replying so fast. Saying this i think this issue can be close.
