### ISSUE TITLE
crash when playing requiem of the phantasma

### ISSUE THREAD

**Issue by JaegerFox** [korenkonder/DivaGL#9]
I'm not sure if it's a DivaGL or PDLoader issue, but this song (I don't know if there are any others) crashes after the loading screen..
I've checked the checksum of my files and they're all ok except mdata/M271 (missing)
Another song I'm having trouble with is Luka Luka Night Fever, when Tako Luka appears, Luka just stops without making a move

If I post this here, it's because I have an AMD graphics card and maybe that could cause problems.

**Comment by korenkonder** [comment]
Fixed the first issue with recent Release v0.7.2.1.

Sadly, I can't help with the second issue since it's not a DivaGL issue.
